### ISSUE TITLE
老哥，有兴趣一起共建 umijs/hooks 吗？

### ISSUE THREAD

**Issue by brickspert** [shiheng-fe/hooks#1]
😋

**Comment by DiamondYuan** [comment]
> 😋

umijs/hooks 很不错，但是我们不想依赖 react-use，所以会从 umijs/hooks 移植一部分的 hooks 过来。
等有修改时，会贡献到  umijs/hooks 里面。

**Comment by brickspert** [comment]
@DiamondYuan 我们这两天也有讨论过 react-use 的问题，我们后面也会沉淀基础 hooks 进去的。还是希望能一起共建。😋
